"""add hosted strategy models

Revision ID: 5b35c717713d
Revises: aa8fa5c74ed6
Create Date: 2026-03-28 14:22:07.590532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b35c717713d'
down_revision: Union[str, None] = 'aa8fa5c74ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entrypoint', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_codes_tenant_id'), 'strategy_codes', ['tenant_id'], unique=False)
    op.create_table('strategy_code_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_code_id'], ['strategy_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_code_id', 'version')
    )
    op.create_index(op.f('ix_strategy_code_versions_strategy_code_id'), 'strategy_code_versions', ['strategy_code_id'], unique=False)
    op.create_index(op.f('ix_strategy_code_versions_tenant_id'), 'strategy_code_versions', ['tenant_id'], unique=False)
    op.create_table('strategy_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_version_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('broker_connection_id', sa.Uuid(), nullable=True),
    sa.Column('cron_expression', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('promoted_from_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ),
    sa.ForeignKeyConstraint(['promoted_from_id'], ['strategy_deployments.id'], ),
    sa.ForeignKeyConstraint(['strategy_code_id'], ['strategy_codes.id'], ),
    sa.ForeignKeyConstraint(['strategy_code_version_id'], ['strategy_code_versions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_deployments_strategy_code_id'), 'strategy_deployments', ['strategy_code_id'], unique=False)
    op.create_index(op.f('ix_strategy_deployments_tenant_id'), 'strategy_deployments', ['tenant_id'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_logs_deployment_id'), 'deployment_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_logs_tenant_id'), 'deployment_logs', ['tenant_id'], unique=False)
    op.create_table('deployment_states',
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('open_orders', sa.JSON(), nullable=False),
    sa.Column('portfolio', sa.JSON(), nullable=False),
    sa.Column('user_state', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_index(op.f('ix_deployment_states_tenant_id'), 'deployment_states', ['tenant_id'], unique=False)
    op.add_column('strategy_results', sa.Column('deployment_id', sa.Uuid(), nullable=True))
    op.add_column('strategy_results', sa.Column('strategy_code_version_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_strategy_results_deployment_id', 'strategy_results', 'strategy_deployments', ['deployment_id'], ['id'])
    op.create_foreign_key('fk_strategy_results_strategy_code_version_id', 'strategy_results', 'strategy_code_versions', ['strategy_code_version_id'], ['id'])
    # ### end Alembic commands ###

    # RLS policies for new tables
    for table in ["strategy_codes", "strategy_code_versions", "strategy_deployments", "deployment_states", "deployment_logs"]:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = current_setting('app.current_tenant_id')::UUID)"
        )


def downgrade() -> None:
    # RLS policies teardown
    for table in ["strategy_codes", "strategy_code_versions", "strategy_deployments", "deployment_states", "deployment_logs"]:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_strategy_results_strategy_code_version_id', 'strategy_results', type_='foreignkey')
    op.drop_constraint('fk_strategy_results_deployment_id', 'strategy_results', type_='foreignkey')
    op.drop_column('strategy_results', 'strategy_code_version_id')
    op.drop_column('strategy_results', 'deployment_id')
    op.drop_index(op.f('ix_deployment_states_tenant_id'), table_name='deployment_states')
    op.drop_table('deployment_states')
    op.drop_index(op.f('ix_deployment_logs_tenant_id'), table_name='deployment_logs')
    op.drop_index(op.f('ix_deployment_logs_deployment_id'), table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_strategy_deployments_tenant_id'), table_name='strategy_deployments')
    op.drop_index(op.f('ix_strategy_deployments_strategy_code_id'), table_name='strategy_deployments')
    op.drop_table('strategy_deployments')
    op.drop_index(op.f('ix_strategy_code_versions_tenant_id'), table_name='strategy_code_versions')
    op.drop_index(op.f('ix_strategy_code_versions_strategy_code_id'), table_name='strategy_code_versions')
    op.drop_table('strategy_code_versions')
    op.drop_index(op.f('ix_strategy_codes_tenant_id'), table_name='strategy_codes')
    op.drop_table('strategy_codes')
    # ### end Alembic commands ###
