"""add_deployment_trade

Revision ID: 919540c9ed52
Revises: b6e74168570e
Create Date: 2026-03-28 17:11:28.487461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919540c9ed52'
down_revision: Union[str, None] = 'b6e74168570e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('trigger_price', sa.Numeric(), nullable=True),
    sa.Column('fill_price', sa.Numeric(), nullable=True),
    sa.Column('fill_quantity', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_trades_deployment_id'), 'deployment_trades', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_trades_tenant_id'), 'deployment_trades', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # RLS policy for deployment_trades
    op.execute("ALTER TABLE deployment_trades ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation ON deployment_trades
        USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
    """)


def downgrade() -> None:
    # RLS policy teardown
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON deployment_trades")
    op.execute("ALTER TABLE deployment_trades DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_trades_tenant_id'), table_name='deployment_trades')
    op.drop_index(op.f('ix_deployment_trades_deployment_id'), table_name='deployment_trades')
    op.drop_table('deployment_trades')
    # ### end Alembic commands ###
