"""paper_sessions_hosted_strategy_support

Revision ID: b6e74168570e
Revises: 5b35c717713d
Create Date: 2026-03-28 11:04:17.731692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e74168570e'
down_revision: Union[str, None] = '5b35c717713d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
